/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:aa060705-f945-4d6c-ae82-787726cf7ac4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7E4Qhjhd7",
    "aws_user_pools_web_client_id": "5keu3ikis219ll7jr4jjk1feqk",
    "oauth": {},
    "aws_user_files_s3_bucket": "mentor-mentee-matching-bucket190958-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_mobile_analytics_app_id": "e536884a49a649078bccc0de59c5c1d5",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
