/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3e2137f6-f85d-43f8-8757-92f7c8911eab",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_l64cjeby4",
    "aws_user_pools_web_client_id": "722c7923a25pchutkqpgdrl9ih",
    "oauth": {},
    "aws_user_files_s3_bucket": "inclusive-content-audit-tool-bucket163110-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
